apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "2"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"memo"},"name":"memo","namespace":"memo"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"memo"}},"template":{"metadata":{"labels":{"app":"memo"}},"spec":{"containers":[{"image":"m4tt4r/memo:0.1.1","name":"memo","ports":[{"containerPort":8000}],"resources":{"limits":{"cpu":"1000m","memory":"512Mi"},"requests":{"cpu":"250m","memory":"64Mi"}}}]}}}}
    creationTimestamp: "2024-07-16T12:23:33Z"
    generation: 2
    labels:
      app: memo
    name: memo
    namespace: memo
    resourceVersion: "85066"
    uid: 1a9ae0f3-0e87-4a54-83df-b50ee75677c0
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: memo
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: memo
      spec:
        containers:
        - image: m4tt4r/memo:0.1.1
          imagePullPolicy: IfNotPresent
          name: memo
          ports:
          - containerPort: 8000
            protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 64Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2024-07-16T12:23:33Z"
      lastUpdateTime: "2024-07-16T12:28:14Z"
      message: ReplicaSet "memo-7cd7766c77" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2024-07-19T19:43:23Z"
      lastUpdateTime: "2024-07-19T19:43:23Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 2
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
